### ISSUE TITLE
How to visit FTP link,thanks you sosososo much!!!

### ISSUE THREAD

**Issue by vvvvvair** [vishnubk/sgan#1]
sor,I don't know how to visit FTP link ,can you give me some guides? thanks you!!!

**Comment by vishnubk** [comment]
Try wget followed by the path. 

For example: 
wget ftp.mpifr-bonn.mpg.de:outgoing/vishnu/sgan_data/sgan_lowlat_raw_dataset.tar.gz

Closing this issue now..
