### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by Cyanglll** [vishnubk/sgan#3]
Dear predecessor：
I'm an astronomer studying pulsars, currently in my second year of graduate school. I was recently reading your paper on pulsar identification and was very interested in your work. First of all, I admire you for doing such a brilliant experiment!!!
I'm getting the following error when downloading the dataset.  I guess it's because I don't have permission or the folder is empty. Sincerely, can I contact you privately to get the relevant data? My email is cyang_lv@163.com or qq is 2754064664.
Secondly, it's a struggle to do experiments in this area, and I'm very sincerely inviting seniors to give me advice.
`ubuntu:~$ wget ftp://ftp.mpifr-bonn.mpg.de/outgoing/vishnu/sgan_data/downsampled_normalised_data.tar.gz
--2024-08-27 22:27:43--  ftp://ftp.mpifr-bonn.mpg.de/outgoing/vishnu/sgan_data/downsampled_normalised_data.tar.gz
           => ‘downsampled_normalised_data.tar.gz’
Resolving ftp.mpifr-bonn.mpg.de (ftp.mpifr-bonn.mpg.de)... 134.104.18.103
Connecting to ftp.mpifr-bonn.mpg.de (ftp.mpifr-bonn.mpg.de)|134.104.18.103|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /outgoing/vishnu/sgan_data ... 
No such directory ‘outgoing/vishnu/sgan_data’.
`

**Comment by vishnubk** [comment]
Please try the FTP download links again. They were broken for a while, but have now been restored.
